services:
   nginx:
     build:
      context: .
      dockerfile: CurtNetWebnginx/dockerfile
     ports:
       - "80:80"
     networks:
       - internal
   php:
     build:
      context: .
      dockerfile: CurtNetWebPHP/dockerfile
     networks:
        - internal
networks:
  internal:
    driver: bridge