services:
   nginx:
     image: curtnet/curtweb-nginx
     ports:
       - "80:80"
     networks:
       - internal
   php:
     image: curtnet/curtweb-php
     networks:
        - internal
networks:
  internal:
    driver: bridge